---
title: "고급심리통계 HW6"
author: "Jahye, Kim"
date: "6/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 0.데이터의 입력

```{r}
setwd('/Users/jangjaeho/GoogleDrive/Research/StatConsult/Soomgo/2006/김자혜')
# hw <- read.table('./hw6_1.txt', header = T)
hw <- data.frame(X1 = rnorm(100), X2 = rnorm(100))
hw$Y <- 1.31 * hw$X1 - 0.45 * hw$X2 + rnorm(100)
# hw$Y <- rnorm(100)
head(hw)
```

### 1. 위계적 회귀분석

#### 1.1. 1단계와 2단계 사이의 $R^2$ 변화량
```{r}
M1 <- lm(Y ~ X1, data = hw)
M2 <- update(M1, ~ . + X2)

M1.rsq <- summary(M1)$r.squared
M2.rsq <- summary(M2)$r.squared
rsq.diff <- (M2.rsq - M1.rsq) * 100
```

$R^2$ 변화량 = `r rsq.diff`%

#### 1.2. 1.1.에서 구한 통계량의 유의성 검정
```{r}
anova(M1, M2)
```

#### 1.3. 1.2.에서 최종모형 해석
```{r}
summary(M2)
```

#### 1.4. M3의 적합
```{r}
M3 <- lm(Y ~ X2, data = hw)
summary(M3)
```

### 2. 범주형 독립변인
```{r}
hw <-
  data.frame(X1 = rnorm(100), X2 = factor(sample(c('Male', 'Female'), 100, replace = T)))
hw$X2.dum <- ifelse(hw$X2 == 'Male', 0, 1)
hw$Y <- 1.31 * hw$X1 -  .45 * hw$X2.dum + rnorm(100)
summary(lm(Y ~ X1 + X2, data = hw))
```